version: '3.8'

services:
  exchanger-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: exchanger
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - exchanger-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  wallet-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: wallet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - wallet-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  exchanger:
    build:
      context: .
      dockerfile: exchanger/Dockerfile
    depends_on:
      exchanger-db:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "50051:50051"
    volumes:
      - ./exchanger/migrations:/app/migrations

  wallet:
    build:
      context: .
      dockerfile: wallet/Dockerfile
    depends_on:
      wallet-db:
        condition: service_healthy
      exchanger:
        condition: service_started
    ports:
      - "8081:8081"
    volumes:
      - ./wallet/migrations:/app/migrations

volumes:
  exchanger-db-data:
  wallet-db-data: