services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "6543:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - exchange-net

  exchanger:
    build:
      context: .
      dockerfile: exchanger/Dockerfile
    depends_on:
      - postgres
    environment:
      DB_URL: postgres://postgres:postgres@postgres:5432/exchanger?sslmode=disable
      SERVER_PORT: 8080
    ports:
      - "8081:8080"
      - "50051:50051"
    networks:
      - exchange-net

  wallet:
    build:
      context: .
      dockerfile: wallet/Dockerfile
    depends_on:
      - postgres
      - exchanger
    environment:
      DB_URL: postgres://postgres:postgres@postgres:5432/wallet?sslmode=disable
      SERVER_PORT: 8080
      EXCHANGER_GRPC_ADDR: exchanger:50051
    ports:
      - "8080:8080"
    networks:
      - exchange-net

volumes:
  postgres_data:

networks:
  exchange-net:
    driver: bridge
