openapi: 3.0.0
info:
  title: Wallet Service API
  description: API for user registration, authentication, wallet operations and currency exchange
  version: 1.0.0
servers:
  - url: /api/v1
    description: Main API server

paths:
  /register:
    post:
      tags:
        - Authentication
      summary: Register a new user
      description: Register a new user with username, password and email
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                email:
                  type: string
              required:
                - username
                - password
                - email
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User registered successfully
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Username or email already exists

  /login:
    post:
      tags:
        - Authentication
      summary: Authenticate user
      description: Authenticate user and return JWT token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '200':
          description: Successful authentication
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid username or password

  /balance:
    get:
      tags:
        - Wallet
      summary: Get user balance
      description: Returns current balance for all currencies
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  balance:
                    type: object
                    properties:
                      USD:
                        type: number
                        format: float
                      RUB:
                        type: number
                        format: float
                      EUR:
                        type: number
                        format: float

  /wallet/deposit:
    post:
      tags:
        - Wallet
      summary: Deposit funds
      description: Add funds to user's wallet
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                  format: float
                  example: 100.00
                currency:
                  type: string
                  enum: [USD, RUB, EUR]
              required:
                - amount
                - currency
      responses:
        '200':
          description: Deposit successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Account topped up successfully
                  new_balance:
                    type: object
                    properties:
                      USD:
                        type: number
                        format: float
                      RUB:
                        type: number
                        format: float
                      EUR:
                        type: number
                        format: float
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid amount or currency

  /wallet/withdraw:
    post:
      tags:
        - Wallet
      summary: Withdraw funds
      description: Withdraw funds from user's wallet
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                  format: float
                  example: 50.00
                currency:
                  type: string
                  enum: [USD, RUB, EUR]
              required:
                - amount
                - currency
      responses:
        '200':
          description: Withdrawal successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Withdrawal successful
                  new_balance:
                    type: object
                    properties:
                      USD:
                        type: number
                        format: float
                      RUB:
                        type: number
                        format: float
                      EUR:
                        type: number
                        format: float
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Insufficient funds or invalid amount

  /exchange/rates:
    get:
      tags:
        - Exchange
      summary: Get exchange rates
      description: Returns current exchange rates for all supported currencies
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  rates:
                    type: object
                    properties:
                      USD:
                        type: number
                        format: float
                      RUB:
                        type: number
                        format: float
                      EUR:
                        type: number
                        format: float
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Failed to retrieve exchange rates

  /exchange:
    post:
      tags:
        - Exchange
      summary: Exchange currency
      description: Exchange one currency to another using current rates
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                from_currency:
                  type: string
                  enum: [USD, RUB, EUR]
                to_currency:
                  type: string
                  enum: [USD, RUB, EUR]
                amount:
                  type: number
                  format: float
                  example: 100.00
              required:
                - from_currency
                - to_currency
                - amount
      responses:
        '200':
          description: Exchange successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Exchange successful
                  exchanged_amount:
                    type: number
                    format: float
                    example: 85.00
                  new_balance:
                    type: object
                    properties:
                      USD:
                        type: number
                        format: float
                      RUB:
                        type: number
                        format: float
                      EUR:
                        type: number
                        format: float
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Insufficient funds or invalid currencies

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT