// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: api/exchanger.proto

package api

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExchangerService_GetRates_FullMethodName = "/exchanger.ExchangerService/GetRates"
)

// ExchangerServiceClient is the client API for ExchangerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExchangerServiceClient interface {
	GetRates(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RatesResponse, error)
}

type exchangerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExchangerServiceClient(cc grpc.ClientConnInterface) ExchangerServiceClient {
	return &exchangerServiceClient{cc}
}

func (c *exchangerServiceClient) GetRates(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RatesResponse)
	err := c.cc.Invoke(ctx, ExchangerService_GetRates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExchangerServiceServer is the server API for ExchangerService service.
// All implementations must embed UnimplementedExchangerServiceServer
// for forward compatibility.
type ExchangerServiceServer interface {
	GetRates(context.Context, *Empty) (*RatesResponse, error)
	mustEmbedUnimplementedExchangerServiceServer()
}

// UnimplementedExchangerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExchangerServiceServer struct{}

func (UnimplementedExchangerServiceServer) GetRates(context.Context, *Empty) (*RatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRates not implemented")
}
func (UnimplementedExchangerServiceServer) mustEmbedUnimplementedExchangerServiceServer() {}
func (UnimplementedExchangerServiceServer) testEmbeddedByValue()                          {}

// UnsafeExchangerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExchangerServiceServer will
// result in compilation errors.
type UnsafeExchangerServiceServer interface {
	mustEmbedUnimplementedExchangerServiceServer()
}

func RegisterExchangerServiceServer(s grpc.ServiceRegistrar, srv ExchangerServiceServer) {
	// If the following call pancis, it indicates UnimplementedExchangerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExchangerService_ServiceDesc, srv)
}

func _ExchangerService_GetRates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExchangerServiceServer).GetRates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExchangerService_GetRates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExchangerServiceServer).GetRates(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ExchangerService_ServiceDesc is the grpc.ServiceDesc for ExchangerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExchangerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "exchanger.ExchangerService",
	HandlerType: (*ExchangerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRates",
			Handler:    _ExchangerService_GetRates_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/exchanger.proto",
}
