// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/exchanger.proto

package api

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_exchanger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_exchanger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_exchanger_proto_rawDescGZIP(), []int{0}
}

type RatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rates         map[string]float64     `protobuf:"bytes,1,rep,name=rates,proto3" json:"rates,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RatesResponse) Reset() {
	*x = RatesResponse{}
	mi := &file_api_exchanger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RatesResponse) ProtoMessage() {}

func (x *RatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_exchanger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RatesResponse.ProtoReflect.Descriptor instead.
func (*RatesResponse) Descriptor() ([]byte, []int) {
	return file_api_exchanger_proto_rawDescGZIP(), []int{1}
}

func (x *RatesResponse) GetRates() map[string]float64 {
	if x != nil {
		return x.Rates
	}
	return nil
}

var File_api_exchanger_proto protoreflect.FileDescriptor

const file_api_exchanger_proto_rawDesc = "" +
	"\n" +
	"\x13api/exchanger.proto\x12\texchanger\"\a\n" +
	"\x05Empty\"\x84\x01\n" +
	"\rRatesResponse\x129\n" +
	"\x05rates\x18\x01 \x03(\v2#.exchanger.RatesResponse.RatesEntryR\x05rates\x1a8\n" +
	"\n" +
	"RatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x012J\n" +
	"\x10ExchangerService\x126\n" +
	"\bGetRates\x12\x10.exchanger.Empty\x1a\x18.exchanger.RatesResponseB\x12Z\x10/api;exchangerpbb\x06proto3"

var (
	file_api_exchanger_proto_rawDescOnce sync.Once
	file_api_exchanger_proto_rawDescData []byte
)

func file_api_exchanger_proto_rawDescGZIP() []byte {
	file_api_exchanger_proto_rawDescOnce.Do(func() {
		file_api_exchanger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_exchanger_proto_rawDesc), len(file_api_exchanger_proto_rawDesc)))
	})
	return file_api_exchanger_proto_rawDescData
}

var file_api_exchanger_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_exchanger_proto_goTypes = []any{
	(*Empty)(nil),         // 0: exchanger.Empty
	(*RatesResponse)(nil), // 1: exchanger.RatesResponse
	nil,                   // 2: exchanger.RatesResponse.RatesEntry
}
var file_api_exchanger_proto_depIdxs = []int32{
	2, // 0: exchanger.RatesResponse.rates:type_name -> exchanger.RatesResponse.RatesEntry
	0, // 1: exchanger.ExchangerService.GetRates:input_type -> exchanger.Empty
	1, // 2: exchanger.ExchangerService.GetRates:output_type -> exchanger.RatesResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_exchanger_proto_init() }
func file_api_exchanger_proto_init() {
	if File_api_exchanger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_exchanger_proto_rawDesc), len(file_api_exchanger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_exchanger_proto_goTypes,
		DependencyIndexes: file_api_exchanger_proto_depIdxs,
		MessageInfos:      file_api_exchanger_proto_msgTypes,
	}.Build()
	File_api_exchanger_proto = out.File
	file_api_exchanger_proto_goTypes = nil
	file_api_exchanger_proto_depIdxs = nil
}
